/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.
	- [Measure] By [Dimension]
	- Total Sales By Country
	- Total Quantity By Category
	- Average Price By Product
	- Total Orders By Customer
	
SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/
SELECT * FROM gold.fact_sales;
SELECT * FROM gold.dim_products;
SELECT * FROM gold.dim_customers;

SELECT * FROM gold.dim_products
WHERE category is null;

-- Find total customers by countries
SELECT country, COUNT(*) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT gender, COUNT(*) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT  category, COUNT(*)
FROM gold.dim_products
GROUP BY category;

-- What is the average costs in each category?
SELECT  category, ROUND(AVG(cost),2) AS average_costs
FROM gold.dim_products
GROUP BY category
ORDER BY average_costs DESC;

-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


-- What is the distribution of sold items across countries?
SELECT SUM(sa.quantity), cu.country 
FROM gold.fact_sales sa
LEFT JOIN gold.dim_customers cu
ON cu.customer_key = sa.customer_key
GROUP BY cu.country 
ORDER BY SUM(sa.quantity) DESC;

